#!/usr/bin/python
import sys

def usage():
    print "Usage: "
    print "pattern -c <int>"
    print "pattern -f <hex>"
    exit(0)

#if len(sys.argv) != 3 or len(sys.argv) != 4:
 #   usage()


string = ""
for i in range(len(sys.argv)):
    if sys.argv[i] == "-c":
        num = int(sys.argv[i+1])
        #offset = num % 4
        #actual = num + offset
        letter = 0
        for c in range(num):
            if c % 4 == 0 and c != 0:
                letter += 1
            string += str(chr(0x41 + letter))
        print string
    elif sys.argv[i] == "-f":
        num = int(sys.argv[i+1], 16)
        print chr(num)
    elif i >= len(sys.argv):
        usage()
